name: Run all the Mocha tests
on: 
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mocha-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup latest nodejs"
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - uses: actions/checkout@v3
      - name: "Use yarn to install the dependencies."
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: "Use yarn to run all the mocha tests."
        uses: borales/actions-yarn@v4
        with:
          cmd: test
